pub(super) fn implementation_fingerprint(version: &str) -> String {
    super::super::fingerprint::source_fingerprint(
        version,
        &[
            ("bridge/mod.rs", include_bytes!("mod.rs")),
            ("bridge/fingerprint.rs", include_bytes!("fingerprint.rs")),
            (
                "adapter/package.json",
                include_bytes!("../../../adapters/typescript/package.json"),
            ),
            (
                "adapter/package-lock.json",
                include_bytes!("../../../adapters/typescript/package-lock.json"),
            ),
            (
                "adapter/tsconfig.json",
                include_bytes!("../../../adapters/typescript/tsconfig.json"),
            ),
            (
                "adapter/src/ast-imports.ts",
                include_bytes!("../../../adapters/typescript/src/ast-imports.ts"),
            ),
            (
                "adapter/src/ast.ts",
                include_bytes!("../../../adapters/typescript/src/ast.ts"),
            ),
            (
                "adapter/src/call-classification.ts",
                include_bytes!("../../../adapters/typescript/src/call-classification.ts"),
            ),
            (
                "adapter/src/call-flow.ts",
                include_bytes!("../../../adapters/typescript/src/call-flow.ts"),
            ),
            (
                "adapter/src/call-resolution.ts",
                include_bytes!("../../../adapters/typescript/src/call-resolution.ts"),
            ),
            (
                "adapter/src/call-shared.ts",
                include_bytes!("../../../adapters/typescript/src/call-shared.ts"),
            ),
            (
                "adapter/src/call-targets.ts",
                include_bytes!("../../../adapters/typescript/src/call-targets.ts"),
            ),
            (
                "adapter/src/contract.ts",
                include_bytes!("../../../adapters/typescript/src/contract.ts"),
            ),
            (
                "adapter/src/dataflow.ts",
                include_bytes!("../../../adapters/typescript/src/dataflow.ts"),
            ),
            (
                "adapter/src/dependencies.ts",
                include_bytes!("../../../adapters/typescript/src/dependencies.ts"),
            ),
            (
                "adapter/src/discovery.ts",
                include_bytes!("../../../adapters/typescript/src/discovery.ts"),
            ),
            (
                "adapter/src/emission.ts",
                include_bytes!("../../../adapters/typescript/src/emission.ts"),
            ),
            (
                "adapter/src/model.ts",
                include_bytes!("../../../adapters/typescript/src/model.ts"),
            ),
            (
                "adapter/src/orchestration.ts",
                include_bytes!("../../../adapters/typescript/src/orchestration.ts"),
            ),
            (
                "adapter/src/resolution.ts",
                include_bytes!("../../../adapters/typescript/src/resolution.ts"),
            ),
            (
                "adapter/src/semantic-facts.ts",
                include_bytes!("../../../adapters/typescript/src/semantic-facts.ts"),
            ),
            (
                "adapter/src/semantic-outcomes.ts",
                include_bytes!("../../../adapters/typescript/src/semantic-outcomes.ts"),
            ),
            (
                "adapter/src/svelte.ts",
                include_bytes!("../../../adapters/typescript/src/svelte.ts"),
            ),
        ],
    )
}
