use rustpython_parser::ast::{self, Ranged};

use crate::SourceSpan;

const GENERATED_MARKERS: &[&str] = &[
    "code generated",
    "do not edit",
    "@generated",
    "<auto-generated",
    "auto-generated file",
];

pub fn generated(source: &str) -> bool {
    let head = source
        .get(..source.len().min(4096))
        .unwrap_or(source)
        .to_ascii_lowercase();
    GENERATED_MARKERS.iter().any(|marker| head.contains(marker))
}

pub fn expression_text(expression: &ast::Expr, source: &str) -> String {
    text(expression, source).unwrap_or_else(|| format!("{expression:?}"))
}

pub fn text<T: Ranged>(node: &T, source: &str) -> Option<String> {
    let range = node.range();
    slice(source, usize::from(range.start()), usize::from(range.end()))
        .map(|value| value.trim().to_owned())
}

pub fn span<T: Ranged>(node: &T, path: &str, source: &str) -> Option<SourceSpan> {
    let range = node.range();
    let start = usize::from(range.start());
    let end = usize::from(range.end());
    if start > end || end > source.len() {
        return None;
    }
    let (start_line, start_column) = location(source, start)?;
    let (end_line, end_column) = location(source, end)?;
    Some(SourceSpan {
        end_column,
        end_line,
        path: path.to_owned(),
        start_column,
        start_line,
    })
}

pub fn dotted(expression: &ast::Expr) -> Option<String> {
    match expression {
        ast::Expr::Name(value) => Some(value.id.to_string()),
        ast::Expr::Attribute(value) => {
            let parent = dotted(&value.value)?;
            Some(format!("{parent}.{}", value.attr))
        }
        _ => None,
    }
}

pub fn offset<T: Ranged>(node: &T) -> u32 {
    u32::from(node.start())
}

pub fn end_offset<T: Ranged>(node: &T) -> u32 {
    u32::from(node.end())
}

pub fn byte_location<T: Ranged>(node: &T, source: &str) -> (u64, u64) {
    let offset = usize::from(node.start()).min(source.len());
    let bytes = source.as_bytes();
    let line_start = bytes[..offset]
        .iter()
        .rposition(|byte| *byte == b'\n')
        .map_or(0, |index| index + 1);
    let line = bytes[..offset]
        .iter()
        .filter(|byte| **byte == b'\n')
        .count() as u64
        + 1;
    (line, (offset - line_start) as u64)
}

fn slice(source: &str, start: usize, end: usize) -> Option<String> {
    source
        .as_bytes()
        .get(start..end)
        .and_then(|bytes| std::str::from_utf8(bytes).ok())
        .map(str::to_owned)
}

fn location(source: &str, offset: usize) -> Option<(u64, u64)> {
    if offset > source.len() {
        return None;
    }
    let bytes = source.as_bytes();
    let line_start = bytes[..offset]
        .iter()
        .rposition(|byte| *byte == b'\n')
        .map_or(0, |index| index + 1);
    let line = bytes[..offset]
        .iter()
        .filter(|byte| **byte == b'\n')
        .count() as u64
        + 1;
    let column = std::str::from_utf8(&bytes[line_start..offset])
        .ok()?
        .chars()
        .count() as u64
        + 1;
    Some((line, column))
}
