use rustpython_parser::ast::{self, Ranged};

use crate::SourceSpan;

use super::model::SourceFile;

const GENERATED_MARKERS: &[&str] = &[
    "code generated",
    "do not edit",
    "@generated",
    "<auto-generated",
    "auto-generated file",
];

/// One owner for source byte-offset location queries. Repeatedly scanning a
/// prefix for each AST span made extraction quadratic on large Python files.
#[derive(Debug)]
pub struct LineIndex {
    starts: Vec<usize>,
}

impl LineIndex {
    pub fn new(source: &str) -> Self {
        let mut starts = vec![0];
        for (offset, byte) in source.bytes().enumerate() {
            if byte == b'\n' {
                starts.push(offset + 1);
            }
        }
        Self { starts }
    }

    pub fn retained_bytes(&self) -> usize {
        self.starts.capacity() * std::mem::size_of::<usize>()
    }

    fn line(&self, offset: usize) -> (u64, usize) {
        let index = self.starts.partition_point(|&start| start <= offset) - 1;
        ((index + 1) as u64, self.starts[index])
    }

    fn location(&self, source: &str, offset: usize) -> Option<(u64, u64)> {
        if offset > source.len() {
            return None;
        }
        let (line, start) = self.line(offset);
        let column = source.get(start..offset)?.chars().count() as u64 + 1;
        Some((line, column))
    }

    fn byte_location(&self, offset: usize) -> (u64, u64) {
        let (line, start) = self.line(offset);
        (line, (offset - start) as u64)
    }
}

pub fn generated(source: &str) -> bool {
    let head = source
        .get(..source.len().min(4096))
        .unwrap_or(source)
        .to_ascii_lowercase();
    GENERATED_MARKERS.iter().any(|marker| head.contains(marker))
}

pub fn expression_text(expression: &ast::Expr, source: &str) -> String {
    text(expression, source).unwrap_or_else(|| format!("{expression:?}"))
}

pub fn text<T: Ranged>(node: &T, source: &str) -> Option<String> {
    let range = node.range();
    slice(source, usize::from(range.start()), usize::from(range.end()))
        .map(|value| value.trim().to_owned())
}

pub fn span<T: Ranged>(node: &T, file: &SourceFile) -> Option<SourceSpan> {
    let range = node.range();
    let start = usize::from(range.start());
    let end = usize::from(range.end());
    if start > end || end > file.source.len() {
        return None;
    }
    let (start_line, start_column) = file.lines.location(&file.source, start)?;
    let (end_line, end_column) = file.lines.location(&file.source, end)?;
    Some(SourceSpan {
        end_column,
        end_line,
        path: file.relative.clone(),
        start_column,
        start_line,
    })
}

pub fn dotted(expression: &ast::Expr) -> Option<String> {
    match expression {
        ast::Expr::Name(value) => Some(value.id.to_string()),
        ast::Expr::Attribute(value) => {
            let parent = dotted(&value.value)?;
            Some(format!("{parent}.{}", value.attr))
        }
        _ => None,
    }
}

pub fn offset<T: Ranged>(node: &T) -> u32 {
    u32::from(node.start())
}

pub fn end_offset<T: Ranged>(node: &T) -> u32 {
    u32::from(node.end())
}

pub fn byte_location<T: Ranged>(node: &T, file: &SourceFile) -> (u64, u64) {
    let offset = usize::from(node.start()).min(file.source.len());
    file.lines.byte_location(offset)
}

fn slice(source: &str, start: usize, end: usize) -> Option<String> {
    source
        .as_bytes()
        .get(start..end)
        .and_then(|bytes| std::str::from_utf8(bytes).ok())
        .map(str::to_owned)
}

#[cfg(test)]
mod tests {
    use super::LineIndex;

    fn old_location(source: &str, offset: usize) -> Option<(u64, u64)> {
        let bytes = source.as_bytes();
        let start = bytes
            .get(..offset)?
            .iter()
            .rposition(|b| *b == b'\n')
            .map_or(0, |i| i + 1);
        let line = bytes[..offset].iter().filter(|b| **b == b'\n').count() as u64 + 1;
        let column = source.get(start..offset)?.chars().count() as u64 + 1;
        Some((line, column))
    }

    #[test]
    fn indexed_locations_match_previous_unicode_and_crlf_semantics() {
        for source in [
            "",
            "a\n",
            "π = '😀'\nname = 1\r\nthird\n",
            "first\rsecond\n\n  café\n",
            "𐍈",
        ] {
            let index = LineIndex::new(source);
            for offset in source.char_indices().map(|(i, _)| i).chain([source.len()]) {
                assert_eq!(
                    index.location(source, offset),
                    old_location(source, offset),
                    "char column at byte {offset} in {source:?}"
                );
                let prefix = &source.as_bytes()[..offset];
                let start = prefix
                    .iter()
                    .rposition(|b| *b == b'\n')
                    .map_or(0, |i| i + 1);
                let line = prefix.iter().filter(|b| **b == b'\n').count() as u64 + 1;
                assert_eq!(index.byte_location(offset), (line, (offset - start) as u64));
            }
            assert!(index.location(source, source.len() + 1).is_none());
        }
    }
}
