use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use crate::AdapterError;

const EXCLUDED: &[&str] = &[
    ".arcana",
    ".bundle",
    ".cantrip",
    ".ddocs",
    ".git",
    ".godot",
    ".grimoire",
    ".homunculus",
    ".import",
    ".incubus",
    ".lexicon",
    ".next",
    ".pitlord",
    ".pytest_cache",
    ".ritual",
    ".venv",
    ".warlock",
    ".workingtrees",
    ".worktrees",
    "__pycache__",
    "bin",
    "build",
    "coverage",
    "dist",
    "node_modules",
    "obj",
    "target",
    "tmp",
    "vendor",
    "venv",
];

pub fn collect_sources(
    root: &Path,
    extension: &str,
    selected: &[String],
    incremental: bool,
) -> Result<Vec<String>, AdapterError> {
    if incremental {
        let mut paths = BTreeSet::new();
        for requested in selected {
            let path = normalize_selected(root, requested)?;
            if !path
                .to_ascii_lowercase()
                .ends_with(&extension.to_ascii_lowercase())
                || excluded_path(&path)
            {
                continue;
            }
            let absolute = root.join(path.replace('/', std::path::MAIN_SEPARATOR_STR));
            match fs::metadata(absolute) {
                Ok(metadata) if metadata.is_file() => {
                    paths.insert(path);
                }
                Ok(_) => {}
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
                Err(error) => return Err(AdapterError::from(error)),
            }
        }
        return Ok(paths.into_iter().collect());
    }

    let mut result = Vec::new();
    walk(root, root, extension, &mut result)?;
    result.sort();
    Ok(result)
}

pub fn source_text(content: &[u8]) -> bool {
    std::str::from_utf8(content).is_ok() && !content.contains(&0)
}

pub fn generated_source(content: &[u8]) -> bool {
    let head = &content[..content.len().min(4096)];
    let text = String::from_utf8_lossy(head).to_ascii_lowercase();
    [
        "code generated",
        "do not edit",
        "@generated",
        "<auto-generated",
        "auto-generated file",
    ]
    .iter()
    .any(|marker| text.contains(marker))
}

fn walk(
    root: &Path,
    current: &Path,
    extension: &str,
    result: &mut Vec<String>,
) -> Result<(), AdapterError> {
    let mut entries = fs::read_dir(current)
        .map_err(AdapterError::from)?
        .collect::<Result<Vec<_>, _>>()
        .map_err(AdapterError::from)?;
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let kind = entry.file_type().map_err(AdapterError::from)?;
        let path = entry.path();
        if kind.is_dir() {
            let name = entry.file_name().to_string_lossy().to_ascii_lowercase();
            if EXCLUDED.contains(&name.as_str()) {
                continue;
            }
            walk(root, &path, extension, result)?;
        } else if kind.is_file()
            && path
                .extension()
                .and_then(|value| value.to_str())
                .is_some_and(|value| format!(".{}", value.to_ascii_lowercase()) == extension)
        {
            result.push(relative(root, &path));
        }
    }
    Ok(())
}

fn normalize_selected(root: &Path, requested: &str) -> Result<String, AdapterError> {
    let requested_path = PathBuf::from(requested.replace('/', std::path::MAIN_SEPARATOR_STR));
    let relative = if requested_path.is_absolute() {
        requested_path
            .strip_prefix(root)
            .map_err(|_| AdapterError::new(format!("source path escapes repository: {requested}")))?
            .to_path_buf()
    } else {
        requested_path
    };
    let normalized = relative.to_string_lossy().replace('\\', "/");
    if normalized == ".." || normalized.starts_with("../") {
        return Err(AdapterError::new(format!(
            "source path escapes repository: {requested}"
        )));
    }
    Ok(normalized)
}

fn relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn excluded_path(path: &str) -> bool {
    path.split('/')
        .any(|part| EXCLUDED.contains(&part.to_ascii_lowercase().as_str()))
}
